let app = getApp();

Page({
    data: {
        "templateId": 51420,
        "styleId": "477702",
        "title": "NIKE耐克男小童运动鞋",
        "subtitle": "PHYLITE中底设计，超强弹性耐久性，减少有害弯曲。",
        "typeId": 137,
        "itemId": 314622,
        "itemPic": "http://img.mamhao.cn/477702/sku_477702L140203Y.jpg",
        "isCollect": false,
        "mamCare": "这款耐克网眼运动鞋，采用简约网眼鞋面，设计精美，完美包裹双足之余，缔造透气轻盈的穿着感受。PHYLITE中底设计，能有效减少有害弯曲。外底搭载匠心排布的橡胶垫显著提升高磨损区的耐磨性。整体的设计简约而不简单，采用合成革鞋面结合网布拼片，透气性佳，穿着舒适。",
        "graphicDetails": "http://image.mamhao.cn/477702/1484108507723.html?time\u003d1491891043344",
        "styleHtml": "\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_01.jpg\" /\u003e\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_02.jpg\" /\u003e\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_03.jpg\" /\u003e\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_04.jpg\" /\u003e\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_05.jpg\" /\u003e\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_06.jpg\" /\u003e\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_07.jpg\" /\u003e\u003cimg src\u003d\"http://image.mamhao.cn/477702/detail_477702_08.jpg\" /\u003e",
        "quality": 0,
        "totalSaleCount": 55,
        "formartTotalSale": "55",
        "online": 1,
        "shopType": 1,
        "shop": "好孩子西湖银泰组合店",
        "mailPriceTerm": 59.0,
        "mailPrice": 10.0,
        "specialistName": "王芹",
        "specialistPhoto": "http://type-images.oss-cn-hangzhou.aliyuncs.com/137.jpg",
        "mBean": 0,
        "getmBean": 499,
        "companyId": 31,
        "shopId": 13235,
        "price": 499.0,
        "originalPrice": 499.0,
        "isKuaidi": false,
        "isViewCart": true,
        "isViewDirect": true,
        "isInStock": true,
        "isNotSale": 0,
        "pic": ["http://img.mamhao.cn/477702/main_477702402_01.jpg", "http://img.mamhao.cn/477702/main_477702402_02.jpg", "http://img.mamhao.cn/477702/main_477702402_03.jpg", "http://img.mamhao.cn/477702/main_477702402_04.jpg", "http://img.mamhao.cn/477702/main_477702402_05.jpg"],
        "specs": [{
            "itemId": 314622,
            "isUp": true,
            "spec": [{"key": "颜色", "value": "红色"}, {"key": "尺寸", "value": "3Y/22cm"}],
            "skuComparator": {}
        }, {
            "itemId": 314627,
            "isUp": true,
            "spec": [{"key": "颜色", "value": "清水蓝"}, {"key": "尺寸", "value": "12C/18cm"}],
            "skuComparator": {}
        }, {
            "itemId": 314620,
            "isUp": true,
            "spec": [{"key": "颜色", "value": "红色"}, {"key": "尺寸", "value": "1Y/20cm"}],
            "skuComparator": {}
        }, {
            "itemId": 314625,
            "isUp": true,
            "spec": [{"key": "颜色", "value": "清水蓝"}, {"key": "尺寸", "value": "11C/17cm"}],
            "skuComparator": {}
        }, {
            "itemId": 314621,
            "isUp": true,
            "spec": [{"key": "颜色", "value": "红色"}, {"key": "尺寸", "value": "2Y/21cm"}],
            "skuComparator": {}
        }, {
            "itemId": 314629,
            "isUp": true,
            "spec": [{"key": "颜色", "value": "清水蓝"}, {"key": "尺寸", "value": "13C/19cm"}],
            "skuComparator": {}
        }],
        "goodsTag": [{
            "pic": "http://img.mamhao.cn/tags/7.png",
            "view": "7天包退",
            "data": "签收7日内，商品不影响二次销售，无条件退货"
        }, {
            "pic": "http://img.mamhao.cn/tags/ziti.png",
            "view": "到店自提",
            "data": "下单后货品可自行前往门店提取"
        }, {
            "pic": "http://img.mamhao.cn/tags/shop.png",
            "view": "门店配送",
            "data": "下单后货品由妈妈好专业配送人员送货上门"
        }, {"pic": "http://img.mamhao.cn/tags/ziying.png", "view": "自营", "data": "自产自销的运营模式"}],
        "deliveryTime": {"beginTime": "", "endTime": "", "arriveType": 0, "isKuaidi": false},
        "priceSection": "499",
        "mbeanSection": "499",
        "isShare": true,
        "shareData": {
            "title": "NIKE耐克男小童运动鞋",
            "desc": "PHYLITE中底设计，超强弹性耐久性，减少有害弯曲。",
            "image": "http://img.mamhao.cn/477702/main_477702402_01.jpg@1e_200w_200h_0c_0i_0o_80q_1x",
            "link": "http://m.mamahao.com/goods/detail/?inlet\u003d6\u0026templateId\u003d51420\u0026itemId\u003d314622"
        },
        "areaId": 330102,
        "styleCatelogThird": 152,
        "maillPriceTxt": "订单总额不满59元,收取运费10元",
        "serviceTxt": "由 好孩子西湖银泰组合店 发货并提供售后服务",
        detailPic: null,
        extInfo: {
            "goodsCouponList": {
                "vouchers": [{
                    "voucherId": "581852910cf2813501efe8c7",
                    "amount": 5.0,
                    "des": "礼包组合券",
                    "applyDes": "老用户礼包券",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "586dece1129989cab6f9c0cd",
                    "amount": 5.0,
                    "des": "满100元减5元",
                    "applyDes": "满减",
                    "timeDes": "领取后2天内有效",
                    "limit": 1000,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": false
                }, {
                    "voucherId": "58184e980cf2813501efe8c3",
                    "amount": 5.0,
                    "des": "礼包组合券",
                    "applyDes": "新用户礼包券",
                    "limit": 2,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "58c8feca0cf23ab205b04b7e",
                    "amount": 5.0,
                    "des": "无金额限制",
                    "applyDes": "下发5元代金券",
                    "timeDes": "领取后2天内有效",
                    "limit": 100,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": false
                }, {
                    "voucherId": "580f1cc466e738438b737ade",
                    "amount": 9.9,
                    "des": "满100元打9.9折",
                    "applyDes": "测试满折券显示小数点",
                    "timeDes": "领取后15天内有效",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 1,
                    "isGiftConpon": false
                }, {
                    "voucherId": "586de95d129989cab6f9c0cc",
                    "amount": 10.0,
                    "des": "无金额限制",
                    "applyDes": "10元无门槛",
                    "timeDes": "领取后2天内有效",
                    "limit": 1000,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": false
                }, {
                    "voucherId": "5819d4ad0cf27da97baddd3f",
                    "amount": 17.0,
                    "des": "礼包组合券",
                    "applyDes": "dev测试礼包券",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "5833b0aa0cf29d8c16b47356",
                    "amount": 23.0,
                    "des": "礼包组合券",
                    "applyDes": "无门槛代金券8块",
                    "limit": 2,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "581aa12e0cf27da97baddd59",
                    "amount": 50.0,
                    "des": "礼包组合券",
                    "applyDes": "test测试的v",
                    "limit": 5,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "581aa26a0cf27da97baddd5a",
                    "amount": 55.0,
                    "des": "礼包组合券",
                    "applyDes": "99999",
                    "limit": 8,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "58131c460cf290b9841f4351",
                    "amount": 63.0,
                    "des": "礼包组合券",
                    "applyDes": "的都的都",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "582430713e3184204d9870bd",
                    "amount": 77.0,
                    "des": "礼包组合券",
                    "applyDes": "测试有效期时分秒礼包",
                    "limit": 10,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "57ff5cbf66e7e02c21b9496a",
                    "amount": 105.0,
                    "des": "礼包组合券",
                    "applyDes": "打发发发",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "586f5aea0cf29d8cc89e78f4",
                    "amount": 111.0,
                    "des": "无金额限制",
                    "applyDes": "沈江测试",
                    "timeDes": "领取后111天内有效",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": false
                }, {
                    "voucherId": "586f59c30cf29d8cc89e78f3",
                    "amount": 111.0,
                    "des": "满1000元减111元",
                    "applyDes": "111",
                    "timeDes": "领取后5天内有效",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": false
                }, {
                    "voucherId": "580d7f5966e77c332d9c2d8e",
                    "amount": 150.0,
                    "des": "礼包组合券",
                    "applyDes": "全场通用满200-50",
                    "limit": 1,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "5810144c0cf290b92950f0ed",
                    "amount": 250.0,
                    "des": "礼包组合券",
                    "applyDes": "礼包组合礼包组合",
                    "limit": 2,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": true
                }, {
                    "voucherId": "58243dcc3e3184204d9870be",
                    "amount": 666.0,
                    "des": "满1111元减666元",
                    "applyDes": "测试几天内有效",
                    "timeDes": "领取后1天内有效",
                    "limit": 10,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": false
                }, {
                    "voucherId": "586dd47c0cf2a1fb5fd6ee6c",
                    "amount": 1800.0,
                    "des": "满1900元减1800元",
                    "applyDes": "全场满1900减1800",
                    "timeDes": "领取后100天内有效",
                    "limit": 100,
                    "isReceive": true,
                    "decreaseType": 0,
                    "isGiftConpon": false
                }]
            },
            "guessYouLike": {
                "data": [{
                    "itemId": 314540,
                    "itemName": "NIKE耐克男小童运动鞋",
                    "styleNumId": 129,
                    "minPrice": 499.0,
                    "pic": "http://img.mamhao.cn/443743/main_443743_01_20161028111731.jpg",
                    "applAge": "12-36",
                    "totalSale": 144,
                    "isHot": 0,
                    "formartTotalSale": "已售144件",
                    "styleId": "443743"
                }, {
                    "itemId": 340021,
                    "itemName": "NIKE耐克毛毛绒系列儿童鞋【婴童】",
                    "styleNumId": 379,
                    "minPrice": 399.0,
                    "pic": "http://img.mamhao.cn/343938/main_343938_01.jpg",
                    "applAge": "3-6,6-12",
                    "totalSale": 7,
                    "isHot": 0,
                    "formartTotalSale": "已售7件",
                    "styleId": "343938"
                }, {
                    "itemId": 314626,
                    "itemName": "NIKE耐克男小童运动鞋",
                    "styleNumId": 51420,
                    "minPrice": 499.0,
                    "pic": "http://img.mamhao.cn/477702/main_477702402_01.jpg",
                    "applAge": "36-84,84-",
                    "totalSale": 55,
                    "isHot": 0,
                    "formartTotalSale": "已售55件",
                    "styleId": "477702"
                }, {
                    "itemId": 339435,
                    "itemName": "NIKE耐克男大童运动鞋",
                    "styleNumId": 168472,
                    "minPrice": 399.0,
                    "pic": "http://img.mamhao.cn/599728/main_599728_01.jpg",
                    "applAge": "84-",
                    "totalSale": 1,
                    "isHot": 0,
                    "formartTotalSale": "已售1件",
                    "styleId": "599728"
                }, {
                    "itemId": 314083,
                    "itemName": "PUMA彪马小童时尚潮流设计运动鞋",
                    "styleNumId": 168519,
                    "minPrice": 399.0,
                    "pic": "http://img.mamhao.cn/PM351980/main_PM351980_01.jpg",
                    "applAge": "12-36,36-84,84-",
                    "totalSale": 39,
                    "isHot": 0,
                    "formartTotalSale": "已售39件",
                    "styleId": "PM351980"
                }, {
                    "itemId": 321180,
                    "itemName": "NIKE耐克时尚运动鞋",
                    "styleNumId": 170288,
                    "minPrice": 379.0,
                    "pic": "http://img.mamhao.cn/629959/main_629959_02.jpg",
                    "applAge": "3-6,6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "629959"
                }, {
                    "itemId": 315049,
                    "itemName": "NIKE FLEX2014 RN（PSV)儿童运动鞋",
                    "styleNumId": 171328,
                    "minPrice": 429.0,
                    "pic": "http://img.mamhao.cn/642759/main_642759_01.jpg",
                    "applAge": "36-84,84-",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "642759"
                }, {
                    "itemId": 314298,
                    "itemName": "NIKE耐克FLEX 2014 RN （TDV）儿童运动鞋",
                    "styleNumId": 171331,
                    "minPrice": 369.0,
                    "pic": "http://img.mamhao.cn/643245/main_643245_01.jpg",
                    "applAge": "-1-0,0-3,3-6,6-12,12-36",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "643245"
                }, {
                    "itemId": 356051,
                    "itemName": "PUMA彪马大童 春秋2015新款运动鞋网面透气跑鞋",
                    "styleNumId": 173087,
                    "minPrice": 549.0,
                    "pic": "http://img.mamhao.cn/PM187254/mian_PM187254_01.jpg",
                    "applAge": "36-84,84-",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "PM187254"
                }, {
                    "itemId": 319647,
                    "itemName": "PUMA彪马婴童 法拉利款运动鞋",
                    "styleNumId": 173091,
                    "minPrice": 459.0,
                    "pic": "http://img.mamhao.cn/PM305168/main_305168_01.jpg",
                    "applAge": "6-12,12-36",
                    "totalSale": 1,
                    "isHot": 0,
                    "formartTotalSale": "已售1件",
                    "styleId": "PM305168"
                }, {
                    "itemId": 304420,
                    "itemName": "Clarks其乐中童JET STOMP INF儿童运动鞋",
                    "styleNumId": 177877,
                    "minPrice": 599.0,
                    "pic": "http://img.mamhao.cn/CL261012928/main_CL261012928_01.jpg",
                    "applAge": "12-36,36-84,84-",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "CL261012928"
                }, {
                    "itemId": 304329,
                    "itemName": "Clarks其乐中童/大童 CROSS DASH拼色皮质运动鞋",
                    "styleNumId": 177910,
                    "minPrice": 599.0,
                    "pic": "http://img.mamhao.cn/CL261025587/main_CL261025587_01.jpg",
                    "applAge": "36-84,84-",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "CL261025587"
                }, {
                    "itemId": 313992,
                    "itemName": "PUMA彪马 婴童/小童时尚皮革运动鞋",
                    "styleNumId": 178981,
                    "minPrice": 359.0,
                    "pic": "http://img.mamhao.cn/PM354348/main_PM354348_01.jpg",
                    "applAge": "6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "PM354348"
                }, {
                    "itemId": 309233,
                    "itemName": "adidas阿迪达斯小童 夏秋新款儿童休闲鞋男女童网面透气运动鞋",
                    "styleNumId": 180266,
                    "minPrice": 499.0,
                    "pic": "http://img.mamhao.cn/ADB24203/main_ADB24203_01.jpg",
                    "applAge": "6-12,12-36",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB24203"
                }, {
                    "itemId": 310595,
                    "itemName": "adidas阿迪达斯小童舒适透气女童鞋",
                    "styleNumId": 180272,
                    "minPrice": 429.0,
                    "pic": "http://img.mamhao.cn/ADB26007/main_ADB26007_01.jpg",
                    "applAge": "12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB26007"
                }, {
                    "itemId": 311463,
                    "itemName": "adidas阿迪达斯小童魔术贴儿童运动鞋",
                    "styleNumId": 180278,
                    "minPrice": 469.0,
                    "pic": "http://img.mamhao.cn/ADB26408/main_ADB26408_01.jpg",
                    "applAge": "12-36,36-84,84-",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB26408"
                }, {
                    "itemId": 309190,
                    "itemName": "adidas阿迪达斯小童时尚炫酷运动鞋",
                    "styleNumId": 180279,
                    "minPrice": 469.0,
                    "pic": "http://img.mamhao.cn/ADB26409/main_ADB26409_01.jpg",
                    "applAge": "6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB26409"
                }, {
                    "itemId": 309925,
                    "itemName": "adidas阿迪达斯婴童秋新款魔术贴童户外鞋防滑运动鞋跑鞋",
                    "styleNumId": 180280,
                    "minPrice": 299.0,
                    "pic": "http://img.mamhao.cn/ADB26423/main_ADB26423_01.jpg",
                    "applAge": "3-6,6-12,12-36",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB26423"
                }, {
                    "itemId": 311319,
                    "itemName": "adidas阿迪达斯三叶草儿童男款运动鞋",
                    "styleNumId": 180296,
                    "minPrice": 599.0,
                    "pic": "http://img.mamhao.cn/ADB39984/main_B39984_01.jpg",
                    "applAge": "3-6,6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB39984"
                }, {
                    "itemId": 311416,
                    "itemName": "adidas阿迪达斯婴童 运动休闲柔软舒适耐磨儿童跑鞋",
                    "styleNumId": 180297,
                    "minPrice": 299.0,
                    "pic": "http://img.mamhao.cn/ADB40084/main_ADB40084_01.jpg",
                    "applAge": "6-12,12-36",
                    "totalSale": 5,
                    "isHot": 0,
                    "formartTotalSale": "已售5件",
                    "styleId": "ADB40084"
                }, {
                    "itemId": 311583,
                    "itemName": "adidas阿迪达斯婴童男款运动鞋",
                    "styleNumId": 180298,
                    "minPrice": 299.0,
                    "pic": "http://img.mamhao.cn/ADB40085/main_ADB40085_01.jpg",
                    "applAge": "6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB40085"
                }, {
                    "itemId": 310065,
                    "itemName": "adidas阿迪达斯小童男款运动鞋  TERREX  GTX  K",
                    "styleNumId": 180305,
                    "minPrice": 699.0,
                    "pic": "http://img.mamhao.cn/ADB40515/main_ADB40515_01.jpg",
                    "applAge": "12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB40515"
                }, {
                    "itemId": 310265,
                    "itemName": "adidas阿迪达斯婴童 女款运动鞋  DISNEY FLUID",
                    "styleNumId": 180309,
                    "minPrice": 399.0,
                    "pic": "http://img.mamhao.cn/ADB40573/main_ADB40573_01.jpg",
                    "applAge": "6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB40573"
                }, {
                    "itemId": 309815,
                    "itemName": "adidas阿迪达斯小童男款运动鞋",
                    "styleNumId": 180313,
                    "minPrice": 529.0,
                    "pic": "http://img.mamhao.cn/ADB40844/main_ADB40844_01.jpg",
                    "applAge": "12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB40844"
                }, {
                    "itemId": 312731,
                    "itemName": "adidas阿迪达斯婴童卡通时尚运动鞋（白/荧光粉）",
                    "styleNumId": 180315,
                    "minPrice": 399.0,
                    "pic": "http://img.mamhao.cn/ADB40940/main_ADB40940_01.jpg",
                    "applAge": "6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB40940"
                }, {
                    "itemId": 309453,
                    "itemName": "adidas阿迪达斯婴童卡通时尚运动鞋（白/幸运蓝）",
                    "styleNumId": 180316,
                    "minPrice": 399.0,
                    "pic": "http://img.mamhao.cn/ADB40941/main_ADB40941_01.jpg",
                    "applAge": "6-12,12-36,36-84",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB40941"
                }, {
                    "itemId": 310011,
                    "itemName": "adidas阿迪达斯婴童网面透气运动鞋",
                    "styleNumId": 180318,
                    "minPrice": 329.0,
                    "pic": "http://img.mamhao.cn/ADB44013/main_ADB44013_01.jpg",
                    "applAge": "3-6,6-12,12-36",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB44013"
                }, {
                    "itemId": 309882,
                    "itemName": "adidas阿迪达斯婴童时尚运动鞋（荧光粉）",
                    "styleNumId": 180319,
                    "minPrice": 329.0,
                    "pic": "http://img.mamhao.cn/ADB44014/main_ADB44014_01.jpg",
                    "applAge": "3-6,6-12",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB44014"
                }, {
                    "itemId": 310838,
                    "itemName": "adidas阿迪达斯大童 时尚运动鞋（空军蓝）",
                    "styleNumId": 180320,
                    "minPrice": 399.0,
                    "pic": "http://img.mamhao.cn/ADB44156/main_ADB44156_01.jpg",
                    "applAge": "36-84,84-",
                    "totalSale": 0,
                    "isHot": 0,
                    "styleId": "ADB44156"
                }]
            },
            "promotionList": [{
                "reservedNo": 14041,
                "promotionName": "D满100减3档",
                "promotionType": 5,
                "landingType": 1,
                "giftGiveType": 0,
                "comboMaxDiscountAmount": 0.0
            }, {
                "reservedNo": 12830,
                "promotionName": "181016促销",
                "promotionType": 3,
                "landingType": 1,
                "giftGiveType": 0,
                "comboMaxDiscountAmount": 0.0,
                "giftGoodsList": [{
                    "styleTitle": "SKECHERS斯凯奇大童TWINKLE TOES女童休闲鞋",
                    "styleNumId": 181016,
                    "styleId": "SK10444LA",
                    "itemNumId": 317637,
                    "itemId": "SK10444LAL1HPMT01Y",
                    "itemName": "TWINKLE TOES",
                    "count": 1,
                    "price": 499.0
                }]
            }],
            "goodsParams": [{"key": "商品名称", "value": "NIKE耐克男小童运动鞋"}, {"key": "品牌名称", "value": "NIKE"}, {
                "key": "适用性别",
                "value": "男宝宝"
            }, {"key": "型号", "value": "477702"}, {"key": "颜色分类", "value": "红色,清水蓝"}, {
                "key": "尺寸分类",
                "value": "1Y/20cm,2Y/21cm,3Y/22cm,10.5C/16.5cm,2.5Y/21.5cm,11C/17cm,12.5C/18.5cm,12C/18cm,13/5C/19.5cm,13C/19cm,1.5Y/20.5cm"
            }],
            "goodsCommentList": {
                "page": 1,
                "resultCount": 2,
                "pageSize": 2,
                "commentCount": 9,
                "percentRate": "100%",
                "rows": [{
                    "itemId": 314620,
                    "templateId": 51420,
                    "babyAge": "1岁1个月4天",
                    "memberId": 384,
                    "orderNo": "11125990853",
                    "name": "杜洋测试服务器",
                    "headPic": "http://cmi.mamhao.cn/member-head-images/384/89ee1dfe83b2ed64d1e92c97b9b06dc9",
                    "star": 5,
                    "commentContent": "呵呵",
                    "pics": ["http://cmi.mamhao.cn/comment-images/384/27489808421fa884a68ff7b857af9b68"],
                    "weight": 304376672700,
                    "commentId": 404,
                    "shopId": 38014,
                    "commenter": 0,
                    "isVip": true,
                    "vipLevel": 2,
                    "vipLevelName": "银粉会员",
                    "vipLevelLogo": "http://bgo.mamhao.cn/purchase/level/vip_level_v2_small.png",
                    "skuInfo": "清水蓝 1Y/20cm "
                }, {
                    "itemId": 314621,
                    "templateId": 51420,
                    "babyAge": "3个月26天",
                    "memberId": 253533,
                    "orderNo": "120170106960994",
                    "name": "但又觉得",
                    "headPic": "http://cmi.mamhao.cn/member-head-images/253533/cf9e20a37c68e12bda48066441e45a5a",
                    "star": 5,
                    "commentContent": "在",
                    "weight": 101481956153,
                    "commentId": 1354,
                    "shopId": 22240,
                    "commenter": 0,
                    "isVip": true,
                    "vipLevel": 3,
                    "vipLevelName": "金粉会员",
                    "vipLevelLogo": "http://bgo.mamhao.cn/purchase/level/vip_level_v3_small.png",
                    "skuInfo": "清水蓝 2Y/21cm "
                }]
            },
            "promoterText": ""
        }
    },
    onLoad (){
        const me = this;
        me.setData({
            detailPic: me.data.styleHtml.match(/http:\/\/\S+.(jpg|png)/gi)
        })
    }
});